version: "2"
linters:
  default: none
  enable:
    - depguard
    - dogsled
    - exhaustive
    - gochecknoinits
    - gocritic
    - goprintffuncname
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - staticcheck
    - unconvert
    - unused
    - whitespace
  settings:
    depguard:
      rules:
        deprecated:
          deny:
            - pkg: io/ioutil
              desc: The 'io/ioutil' package is deprecated. Use corresponding 'os' or 'io' functions instead.
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - storage/ent/db
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/dexidp/dex)
    goimports:
      local-prefixes:
        - github.com/dexidp/dex
  exclusions:
    generated: lax
    paths:
      - storage/ent/db
      - third_party$
      - builtin$
      - examples$
